
import React, { useEffect, useState } from 'react';
import { ScoreDashboard } from './components/ScoreDashboard';
import { HistoryList } from './components/HistoryList';
import { WeatherGrid } from './components/WeatherGrid';
import { YieldChartSection } from './components/YieldChartSection';
import { BondReportData } from './types';
import { bondReports } from './data/bondReports';

const App: React.FC = () => {
  const [reports, setReports] = useState<BondReportData[]>([]);

  useEffect(() => {
    // Load the real data array
    // Ensure data is sorted by generation time descending if not already
    const sortedReports = [...bondReports].sort((a, b) => 
      new Date(b.generated_at).getTime() - new Date(a.generated_at).getTime()
    );
    setReports(sortedReports);
  }, []);

  if (reports.length === 0) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-950">
        <div className="animate-pulse flex flex-col items-center">
          <div className="h-12 w-12 bg-indigo-500/20 rounded-full mb-4"></div>
          <div className="h-4 w-32 bg-slate-800 rounded"></div>
          <p className="mt-4 text-slate-500 text-sm">正在加载数据...</p>
        </div>
      </div>
    );
  }

  // The latest report is the first item in the sorted array
  const latestReport = reports[0];
  const previousReport = reports.length > 1 ? reports[1] : undefined;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 pb-20 selection:bg-indigo-500/30">
      <header className="bg-slate-900 border-b border-slate-800 sticky top-0 z-50 backdrop-blur-md bg-slate-900/80">
        <div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between">
            <div className="flex items-center space-x-2">
                <span className="text-2xl filter drop-shadow-md">🏆</span>
                <span className="font-bold text-slate-100 tracking-tight text-lg">债基晴雨表</span>
            </div>
            <div className="text-xs font-medium px-3 py-1 bg-indigo-950/50 border border-indigo-500/30 text-indigo-300 rounded-full shadow-[0_0_10px_rgba(99,102,241,0.15)]">
                机构级全知全能版
            </div>
        </div>
      </header>

      <main className="space-y-8">
        {/* Section 1: Latest Dashboard (Score & Indicators) */}
        <ScoreDashboard data={latestReport} prevData={previousReport} />

        <div className="max-w-6xl mx-auto px-4 space-y-8">
            {/* Section 2: Weather Grid (Overview) */}
            <WeatherGrid reports={reports} />

            {/* Section 3: History Table */}
            <HistoryList reports={reports} />

            {/* Section 4: Chart (Moved to bottom) */}
            <YieldChartSection data={latestReport.raw.bond_10y} />
        </div>
      </main>

      <footer className="text-center text-slate-500 text-xs py-8 border-t border-slate-900 mt-12">
        <p>© 2025 Bond Fund Smart Investment Advisor. Generated by Python Quant System.</p>
        <p className="mt-2 opacity-60">投资有风险，决策需谨慎。本报告仅供参考。</p>
      </footer>
    </div>
  );
};

export default App;
